env:
  global:
    - secure: "NlWO/NTPlOU6cowOMuPOvjAprXVwIjmpHHf9CoMR71E2c/eBFFKIHj10kXuyFwz2KihHAIExmo9OlGtGniNWobvIrVrabO3dsOSb6UGbPAQkzQiyQLKsDNQAZx3nMuWEKBtMsVRee6rd7/2uGTY4WB5Ot3VhrUYcN1FoRgQQ9gk="

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      env:
        - QT_SELECT=qt5

language: cpp
compiler:
  - gcc
  - clang

script: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make && make test

addons:
  apt:
    update: true
    packages:
    - qt5-default
    - qtbase5-dev
    - qtbase5-dev-tools
    - qttools5-dev
    - qttools5-dev-tools
    - qtdeclarative5-dev
    - qtdeclarative5-dev-tools
    - qtxmlpatterns5-dev-tools
    - graphviz-dev
  homebrew:
    update: true
    packages:
    - qt5
    - graphviz
  coverity_scan:
    project:
      name: KDAB/KDStateMachineEditor
    notification_email: allen.winter@kdab.com
    build_command_prepend: cd build && cmake ..
    build_command: make
    branch_pattern: coverity_scan
