#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}-{branch}

# branches to build
branches:
  except:
    - gh-pages

# Do not build on tags (GitHub and BitBucket)
skip_tags: false

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image
image:
  - Visual Studio 2013

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
  - choco install winflexbison graphviz

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
  - x64

# build Configuration, i.e. Debug, Release, etc.
configuration:
  - Release

install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %PLATFORM%
  - set QTDIR=C:\Qt\5.6\msvc2013_64
  - set GRAPHVIZ_ROOT=c:\Program Files\Graphviz
  - set PATH=%QTDIR%\bin;C:\Python37-x64;%PATH%
build_script:
  - mkdir build
  - cd build
  - cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=%CONFIGURATION% ..
  - nmake

# to disable automatic builds
#build: off

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
  - nmake test

# to disable automatic tests
#test: off


#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy: off

#---------------------------------#
#         notifications           #
#---------------------------------#
notifications:
  # Email
  - provider: Email
    to:
      - allen.winter@kdab.com
      - kevin.funk@kdab.com
    on_build_status_changed: true
